// <auto-generated />
using System;
using MaleFashion.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MaleFashion.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("MaleFashion.Web.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("MaleFashion.Web.Models.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("MaleFashion.Web.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Colors")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OldPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Sizes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Gucci",
                            Category = "Jackets",
                            Colors = "[\"Black\",\"Brown\"]",
                            Description = "Premium biker jacket with a quilted lining and adjustable hood.",
                            ImageUrl = "/img/product/luxury-jacket.png",
                            Label = "New",
                            Name = "Piqué Biker Jacket",
                            Price = 5500m,
                            Rating = 4,
                            Sizes = "[\"M\",\"L\",\"XL\"]",
                            Tags = "[\"Product\",\"Clothing\"]"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Chanel",
                            Category = "Jackets",
                            Colors = "[\"Blue\"]",
                            Description = "A sharp formal suit jacket for men, crafted from premium fabric.",
                            ImageUrl = "/img/product/formal-suit.png",
                            Label = "",
                            Name = "Formal Navy Blazer",
                            Price = 4200m,
                            Rating = 5,
                            Sizes = "[\"S\",\"M\",\"L\"]",
                            Tags = "[\"Product\",\"Clothing\"]"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Hermes",
                            Category = "Shoes",
                            Colors = "[\"Blue\",\"White\"]",
                            Description = "Modern low-top sneakers with a comfortable fit.",
                            ImageUrl = "/img/product/product-1.jpg",
                            Label = "Sale",
                            Name = "Low-top Sneakers",
                            Price = 1800m,
                            Rating = 4,
                            Sizes = "[\"8\",\"9\",\"10\"]",
                            Tags = "[\"Shoes\"]"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Louis Vuitton",
                            Category = "Accessories",
                            Colors = "[\"Grey\"]",
                            Description = "Durable canvas duffel bag for gym or weekend trips.",
                            ImageUrl = "/img/product/product-11.jpg",
                            Label = "",
                            Name = "Canvas Duffel Bag",
                            Price = 2800m,
                            Rating = 5,
                            Sizes = "[\"One Size\"]",
                            Tags = "[\"Bags\",\"Accessories\"]"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Gucci",
                            Category = "Accessories",
                            Colors = "[\"Black\"]",
                            Description = "Sophisticated leather backpack designed for work and travel.",
                            ImageUrl = "/img/product/product-5.jpg",
                            Label = "",
                            Name = "Leather Backpack",
                            Price = 3500m,
                            Rating = 5,
                            Sizes = "[\"One Size\"]",
                            Tags = "[\"Bags\",\"Accessories\"]"
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Chanel",
                            Category = "Shoes",
                            Colors = "[\"Black\"]",
                            Description = "Elegant ankle boots made from genuine leather.",
                            ImageUrl = "/img/product/product-6.jpg",
                            Label = "Sale",
                            Name = "Classic Ankle Boots",
                            Price = 6500m,
                            Rating = 4,
                            Sizes = "[\"8\",\"9\",\"10\"]",
                            Tags = "[\"Shoes\"]"
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Hermes",
                            Category = "Clothing",
                            Colors = "[\"White\",\"Blue\"]",
                            Description = "Casual T-shirt with a unique contrast pocket detail.",
                            ImageUrl = "/img/product/product-7.jpg",
                            Label = "",
                            Name = "T-shirt Contrast Pocket",
                            Price = 1200m,
                            Rating = 5,
                            Sizes = "[\"S\",\"M\",\"L\"]",
                            Tags = "[\"Clothing\"]"
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Louis Vuitton",
                            Category = "Clothing",
                            Colors = "[\"Multi\"]",
                            Description = "Lightweight flowing scarf that adds a touch of elegance.",
                            ImageUrl = "/img/product/product-8.jpg",
                            Label = "",
                            Name = "Basic Flowing Scarf",
                            Price = 850m,
                            Rating = 5,
                            Sizes = "[\"One Size\"]",
                            Tags = "[\"Accessories\"]"
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Gucci",
                            Category = "Clothing",
                            Colors = "[\"Blue\"]",
                            Description = "Classic vintage style blue shirt.",
                            ImageUrl = "/img/product/product-9.jpg",
                            Label = "New",
                            Name = "Vintage Blue Shirt",
                            Price = 2200m,
                            Rating = 4,
                            Sizes = "[\"M\",\"L\",\"XL\"]",
                            Tags = "[\"Clothing\"]"
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Chanel",
                            Category = "Clothing",
                            Colors = "[\"White\"]",
                            Description = "Sharp slim-fit shirt in breathable cotton.",
                            ImageUrl = "/img/product/product-10.jpg",
                            Label = "",
                            Name = "Slim Fit Cotton Shirt",
                            Price = 1950m,
                            Rating = 5,
                            Sizes = "[\"S\",\"M\",\"L\"]",
                            Tags = "[\"Clothing\"]"
                        },
                        new
                        {
                            Id = 11,
                            Brand = "Hermes",
                            Category = "Clothing",
                            Colors = "[\"Grey\"]",
                            Description = "Comfortable casual hoodie with a minimalist design.",
                            ImageUrl = "/img/product/casual-hoodie.png",
                            Label = "Sale",
                            Name = "Casual Grey Hoodie",
                            Price = 2500m,
                            Rating = 4,
                            Sizes = "[\"S\",\"M\",\"L\",\"XL\"]",
                            Tags = "[\"Clothing\"]"
                        },
                        new
                        {
                            Id = 12,
                            Brand = "Louis Vuitton",
                            Category = "Clothing",
                            Colors = "[\"Grey\"]",
                            Description = "Luxurious knit sweater made from fine wool blend.",
                            ImageUrl = "/img/product/product-12.jpg",
                            Label = "",
                            Name = "Premium Knit Sweater",
                            Price = 3800m,
                            Rating = 5,
                            Sizes = "[\"M\",\"L\"]",
                            Tags = "[\"Clothing\"]"
                        },
                        new
                        {
                            Id = 13,
                            Brand = "Gucci",
                            Category = "Clothing",
                            Colors = "[\"Green\"]",
                            Description = "A stylish summer polo shirt in a pastel color.",
                            ImageUrl = "/img/product/summer-polo.png",
                            Label = "",
                            Name = "Classic Polo Shirt",
                            Price = 2800m,
                            Rating = 4,
                            Sizes = "[\"M\",\"L\",\"XL\"]",
                            Tags = "[\"Clothing\"]"
                        },
                        new
                        {
                            Id = 14,
                            Brand = "Chanel",
                            Category = "Accessories",
                            Colors = "[\"Black\"]",
                            Description = "Sleek designer sunglasses with a macro shot perspective.",
                            ImageUrl = "/img/product/designer-sunglasses.png",
                            Label = "",
                            Name = "Aviator Sunglasses",
                            Price = 9000m,
                            Rating = 5,
                            Sizes = "[\"One Size\"]",
                            Tags = "[\"Accessories\"]"
                        },
                        new
                        {
                            Id = 15,
                            Brand = "Hermes",
                            Category = "Accessories",
                            Colors = "[\"Brown\"]",
                            Description = "A luxury men's wristwatch with a leather strap.",
                            ImageUrl = "/img/product/premium-watch.png",
                            Label = "",
                            Name = "Luxury Wristwatch",
                            Price = 15000m,
                            Rating = 5,
                            Sizes = "[\"One Size\"]",
                            Tags = "[\"Accessories\"]"
                        },
                        new
                        {
                            Id = 16,
                            Brand = "Louis Vuitton",
                            Category = "Accessories",
                            Colors = "[\"Black\"]",
                            Description = "Stylish textured cap with a custom fit.",
                            ImageUrl = "/img/product/product-4.jpg",
                            Label = "",
                            Name = "Diagonal Textured Cap",
                            Price = 750m,
                            Rating = 5,
                            Sizes = "[\"One Size\"]",
                            Tags = "[\"Hats\",\"Accessories\"]"
                        },
                        new
                        {
                            Id = 17,
                            Brand = "Gucci",
                            Category = "Accessories",
                            Colors = "[\"Black\"]",
                            Description = "Practical urban backpack for daily use.",
                            ImageUrl = "/img/product/product-2.jpg",
                            Label = "",
                            Name = "Urban Utility Backpack",
                            Price = 3200m,
                            Rating = 4,
                            Sizes = "[\"One Size\"]",
                            Tags = "[\"Bags\"]"
                        },
                        new
                        {
                            Id = 18,
                            Brand = "Chanel",
                            Category = "Accessories",
                            Colors = "[\"Black\"]",
                            Description = "Versatile chest bag with multiple compartments.",
                            ImageUrl = "/img/product/product-3.jpg",
                            Label = "",
                            Name = "Multi-pocket Chest Bag",
                            Price = 1500m,
                            Rating = 5,
                            Sizes = "[\"One Size\"]",
                            Tags = "[\"Bags\"]"
                        },
                        new
                        {
                            Id = 19,
                            Brand = "Hermes",
                            Category = "Accessories",
                            Colors = "[\"Brown\"]",
                            Description = "High-quality leather belt with a timeless design.",
                            ImageUrl = "/img/product/product-13.jpg",
                            Label = "",
                            Name = "Premium Leather Belt",
                            Price = 4500m,
                            Rating = 5,
                            Sizes = "[\"M\",\"L\"]",
                            Tags = "[\"Accessories\"]"
                        },
                        new
                        {
                            Id = 20,
                            Brand = "Louis Vuitton",
                            Category = "Accessories",
                            Colors = "[\"Black\"]",
                            Description = "Sleek designer wallet for minimalists.",
                            ImageUrl = "/img/product/product-14.jpg",
                            Label = "",
                            Name = "Designer Slim Wallet",
                            Price = 6000m,
                            Rating = 5,
                            Sizes = "[\"One Size\"]",
                            Tags = "[\"Accessories\"]"
                        });
                });

            modelBuilder.Entity("MaleFashion.Web.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "admin-1",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@smashcollections.com",
                            IsActive = true,
                            IsAdmin = true,
                            Password = "admin",
                            PhoneNumber = "0000000000",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("MaleFashion.Web.Models.WishlistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("WishlistItems");
                });

            modelBuilder.Entity("MaleFashion.Web.Models.CartItem", b =>
                {
                    b.HasOne("MaleFashion.Web.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MaleFashion.Web.Models.WishlistItem", b =>
                {
                    b.HasOne("MaleFashion.Web.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
